// src/online/task_planner.rs - Multi-step task planning data structures & parsing
// Execution is handled in main.rs where it has access to app state.

use crate::online::reasoning::extract_json_string_field;
use serde::{Deserialize, Serialize};

/// A single step in a chained task plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskStep {
    pub tool: String,
    pub args: String,
    pub description: String,
}

/// A multi-step plan generated by the LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskPlan {
    pub steps: Vec<TaskStep>,
    pub summary: String,
}

/// Result of executing one step
#[derive(Debug, Clone)]
pub struct StepResult {
    pub tool: String,
    pub message: String,
}

/// Parse an LLM response that may contain a single tool call or multiple.
/// Supports:
///   - `{"tool":"...","args":{...}}` (single)
///   - `[{"tool":"...","args":{...}}, ...]` (multi)
pub fn parse_llm_response(output: &str) -> Result<TaskPlan, String> {
    let cleaned = strip_code_fences(output);
    let output = cleaned.trim();

    // Try multi-tool (JSON array)
    if let Some(plan) = try_parse_multi_tool(output) {
        return Ok(plan);
    }

    // Handle comma-separated objects WITHOUT outer array brackets.
    // LLM sometimes outputs: {"tool":"open_app",...}, {"tool":"search_web",...}
    if let Some(plan) = try_parse_comma_separated(output) {
        return Ok(plan);
    }

    // Try single tool (JSON object)
    if let Some((tool, args)) = parse_single_tool_object(output) {
        return Ok(TaskPlan {
            steps: vec![TaskStep {
                tool,
                args,
                description: String::new(),
            }],
            summary: String::new(),
        });
    }

    // Try to find ANY JSON array in the output (relaxed)
    if let Some(array_start) = output.find('[') {
        let candidate = &output[array_start..];
        if let Some(plan) = try_parse_multi_tool(candidate) {
            return Ok(plan);
        }
    }

    // Try to find ANY JSON object in the output (relaxed)
    if let Some(obj_start) = output.find('{') {
        let candidate = &output[obj_start..];
        if let Some((tool, args)) = parse_single_tool_object(candidate) {
            return Ok(TaskPlan {
                steps: vec![TaskStep {
                    tool,
                    args,
                    description: String::new(),
                }],
                summary: String::new(),
            });
        }
    }

    Err("Could not parse any tool calls from LLM output".to_string())
}

/// Handle comma-separated JSON objects without outer array brackets.
/// e.g. {"tool":"open_app",...}, {"tool":"search_web",...}
fn try_parse_comma_separated(output: &str) -> Option<TaskPlan> {
    let trimmed = output.trim();
    if !trimmed.starts_with('{') {
        return None;
    }

    // Count top-level JSON objects (same depth tracking as try_parse_multi_tool)
    let mut steps = Vec::new();
    let mut depth = 0i32;
    let mut obj_start = None;

    for (i, ch) in trimmed.char_indices() {
        match ch {
            '{' => {
                if depth == 0 {
                    obj_start = Some(i);
                }
                depth += 1;
            }
            '}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(start) = obj_start {
                        let obj = &trimmed[start..=i];
                        if let Some(step) = parse_single_tool_step(obj) {
                            steps.push(step);
                        }
                    }
                    obj_start = None;
                }
            }
            _ => {}
        }
    }

    if steps.len() >= 2 {
        Some(TaskPlan {
            summary: format!("{} tasks", steps.len()),
            steps,
        })
    } else {
        None
    }
}

/// Strip markdown code fences (```json ... ```) and leading/trailing whitespace.
fn strip_code_fences(s: &str) -> String {
    let s = s.trim();
    if s.starts_with("```") {
        let without_start = s.strip_prefix("```").unwrap_or(s);
        // Remove optional language tag on first line
        let first_newline = without_start.find('\n').unwrap_or(0);
        let after_lang = &without_start[(first_newline + 1).min(without_start.len())..];
        // Remove trailing fence
        if let Some(end) = after_lang.rfind("```") {
            after_lang[..end].trim().to_string()
        } else {
            after_lang.trim().to_string()
        }
    } else {
        s.to_string()
    }
}

fn try_parse_multi_tool(output: &str) -> Option<TaskPlan> {
    if !output.starts_with('[') {
        return None;
    }
    let end = output.rfind(']')?;
    let array_str = &output[..=end];

    let mut steps = Vec::new();
    let mut depth = 0i32;
    let mut obj_start = None;

    for (i, ch) in array_str.char_indices() {
        match ch {
            '{' => {
                if depth == 0 {
                    obj_start = Some(i);
                }
                depth += 1;
            }
            '}' => {
                depth -= 1;
                if depth == 0 {
                    if let Some(start) = obj_start {
                        let obj = &array_str[start..=i];
                        if let Some(step) = parse_single_tool_step(obj) {
                            steps.push(step);
                        }
                    }
                    obj_start = None;
                }
            }
            _ => {}
        }
    }

    if steps.is_empty() {
        None
    } else {
        Some(TaskPlan {
            summary: format!("{} tasks", steps.len()),
            steps,
        })
    }
}

fn parse_single_tool_object(json: &str) -> Option<(String, String)> {
    let tool = extract_json_string_field(json, "tool")?;
    let args = extract_args_field(json).unwrap_or_else(|| "{}".to_string());
    Some((tool, args))
}

fn parse_single_tool_step(json: &str) -> Option<TaskStep> {
    let tool = extract_json_string_field(json, "tool")?;
    let args = extract_args_field(json).unwrap_or_else(|| "{}".to_string());
    let desc = extract_json_string_field(json, "description")
        .unwrap_or_else(|| format!("{}", tool));
    Some(TaskStep { tool, args, description: desc })
}

fn extract_args_field(json: &str) -> Option<String> {
    let start = json.find("\"args\"")
        .or_else(|| json.find("\"arguments\""))?;
    let after_field = &json[start..];
    let brace = after_field.find('{')? + start;
    let rest = &json[brace + 1..];
    let end = rest.find('}')? + brace + 1;
    Some(json[brace..=end].to_string())
}
